<?php 
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2009 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 */
?>

<?php if (Mage::helper('creditpass')->moduleActive()): ?>
<script type="text/javascript">
payment.onSave = function(paymentTransport){
	checkout.setLoadWaiting('payment');
	new Ajax.Request(
		'<?php echo Mage::getUrl('creditpass/checkpayment/process'); ?>',
		{
			method:		'get',
			onComplete:	function(transport) {
							if (transport.responseText == 'PASSED') {
								payment.nextStep(paymentTransport);
							} else {
								alert(transport.responseText);
								shippingMethod.save();
							}
						}
		});
};
</script>
<?php endif; ?>